version: '3'

services:
  db:
    image: postgres:14
    container_name: graphql_postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  db-store:
